### ISSUE TITLE
Secure web socket (wss) support for reverse proxying

### ISSUE THREAD

**Issue by chippoman** [3ll3d00d/ezbeq#73]
I created a reverse proxy host for my ezbeq instance. Everything works fine over regular http, but when connecting over https, the console returns the following error:

Mixed Content: The page at 'https://ezbeq.mydomain.net/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://ezbeq.mydomain.net/ws'. This request has been blocked; this endpoint must be available over WSS.

Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at new Nge (https://ezbeq.mydomain.net/assets/index-bb2f419b.js:249:10427)
    at https://ezbeq.mydomain.net/assets/index-bb2f419b.js:249:11538

**Comment by chippoman** [comment]
Nevermind! This is a reverse proxy config issue and nothing to do with ezbeq.

**Comment by openscallion** [comment]
Hi there @chippoman, would you be willing to share your nginx config that allowed you to successfully do this? Thank you!

**Comment by Frick** [comment]
I just ran into this when trying to run ezbeq in kubernetes and since I was already building the container and it's harder to hack on the nginx ingress config, I just rewrote the UI JS to use `wss`. This could probably be fixed fairly trivially by setting the protocol (`ws` vs `wss`) based on `window.location.protocol`. I personally am hosting this on a `.dev` domain which requires HTTPS so this was a must.

To demonstrate, this is all I'm doing with the container:
```Dockerfile
FROM ubuntu:24.04
ENV EZBEQV=2.2.0

RUN apt-get update \
  && apt-get install --no-install-recommends -y python3-pip python3-dev build-essential \
  && rm -rf /var/lib/apt/lists/* \
  && pip install --no-cache-dir --break-system-packages ezbeq==${EZBEQV} \
  && sed -Ei -e 's~ws://~wss://~g' /usr/local/lib/python3*/dist-packages/ezbeq/ui/assets/index-*.js \
  && mkdir -p /srv/ezbeq # mount the config here and set env var EZBEQ_CONFIG_HOME to this

CMD ["ezbeq"]
```

(this is for use with an HTP-1 which does not have other dependencies like `minidsp-rs`)

**Comment by 3ll3d00d** [comment]
@Frick you can try 2.2.1 which incorporates that change to the UI code

**Comment by Frick** [comment]
@3ll3d00d that did the trick! I was able to remove my `sed` line from the above Dockerfile. Thanks for the quick adjustment! 😄 

Now if you have updates to the Python package auto-build [ezbeq-docker](https://github.com/3ll3d00d/ezbeq-docker) with the same version, I'll just use the ghcr.io release instead of my container. 😁
